---
# tasks file for java

- include: setup-deps.yml
  when: "ansible_os_family == 'RedHat'"

- include: setup-common.yml

# Debian(setup)  specific tasks
- include: setup-Debian.yml
  when: "ansible_os_family == 'Debian'"

